#! /bin/sh

rm -rf ./tsparsers/*
cd ./tsparsers

function download {
    git clone --depth 1 --branch master $1 &> /dev/null
    if [[ ! $? ]]; then
        echo "Failed to clone $1"
    else
        echo "Cloned $1"
    fi
}

download https://github.com/tree-sitter/tree-sitter-agda.git
download https://github.com/AbstractMachinesLab/tree-sitter-erlang.git
download https://github.com/tree-sitter/tree-sitter-haskell.git
download https://github.com/tree-sitter/tree-sitter-julia.git
download https://github.com/cstrahan/tree-sitter-nix.git
download https://github.com/ganezdragon/tree-sitter-perl.git
download https://github.com/tree-sitter/tree-sitter-scala.git
download https://github.com/nilshelmig/tree-sitter-sourcepawn.git
download https://github.com/tree-sitter/tree-sitter-swift.git
download https://github.com/tree-sitter/tree-sitter-bash.git
download https://github.com/tree-sitter/tree-sitter-c.git
download https://github.com/tree-sitter/tree-sitter-c-sharp.git
download https://github.com/tree-sitter/tree-sitter-cpp.git
download https://github.com/tree-sitter/tree-sitter-css.git
download https://github.com/elm-tooling/tree-sitter-elm.git
download https://github.com/eno-lang/tree-sitter-eno.git
download https://github.com/tree-sitter/tree-sitter-embedded-template.git
download https://github.com/travonted/tree-sitter-fennel.git
download https://github.com/tree-sitter/tree-sitter-go.git
download https://github.com/tree-sitter/tree-sitter-html.git
download https://github.com/tree-sitter/tree-sitter-java.git
download https://github.com/tree-sitter/tree-sitter-javascript.git
download https://github.com/Azganoth/tree-sitter-lua.git
download https://github.com/ikatyang/tree-sitter-markdown.git
download https://github.com/tree-sitter/tree-sitter-ocaml.git
download https://github.com/tree-sitter/tree-sitter-php.git
download https://github.com/tree-sitter/tree-sitter-python.git
download https://github.com/tree-sitter/tree-sitter-ruby.git
download https://github.com/tree-sitter/tree-sitter-rust.git
download https://github.com/r-lib/tree-sitter-r.git
download https://github.com/AbstractMachinesLab/tree-sitter-sexp.git
download https://github.com/BonaBeavis/tree-sitter-sparql.git
download https://github.com/SystemRDL/tree-sitter-systemrdl.git
download https://github.com/Himujjal/tree-sitter-svelte.git
download https://github.com/ikatyang/tree-sitter-toml.git
download https://github.com/BonaBeavis/tree-sitter-turtle.git
download https://github.com/tree-sitter/tree-sitter-typescript.git
download https://github.com/tree-sitter/tree-sitter-verilog.git
download https://github.com/alemuller/tree-sitter-vhdl.git
download https://github.com/ikatyang/tree-sitter-vue.git
download https://github.com/ikatyang/tree-sitter-yaml.git
download https://github.com/wasm-lsp/tree-sitter-wasm.git
